<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.1 (Python 3.12.6 on darwin)" generated="2024-10-11T00:14:52.517196" rpa="false" schemaversion="5">
<suite id="s1" name="Testcase" source="/Users/khongkhunanat.p/Documents/GitHub/Mobile_Assignment/testcases/testcase.robot">
<test id="s1-t1" name="Verify that in cart has only one product" line="9">
<kw name="Open App" owner="common" type="SETUP">
<kw name="Open Application" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-10-11T00:15:15.971786" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-10-11T00:15:15.971247" elapsed="0.006418">No application is open</status>
</kw>
<msg time="2024-10-11T00:15:15.979034" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-10-11T00:15:15.981244" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
    at getResponseForW3CError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)
    at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)</msg>
<arg>remote_url=http://localhost:4723</arg>
<arg>deviceName=Mobile_Assignment</arg>
<arg>platformVersion="15.0"</arg>
<arg>platformName=Android</arg>
<arg>automationName=uiautomator2</arg>
<arg>appPackage=com.saucelabs.mydemoapp.rn</arg>
<arg>appActivity=com.saucelabs.mydemoapp.rn.MainActivity</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://appium.io/docs/en/2.1/cli/args/
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-10-11T00:14:52.602864" elapsed="23.379219">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
    at getResponseForW3CError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)
    at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)</status>
</kw>
<status status="FAIL" start="2024-10-11T00:14:52.602679" elapsed="23.379612">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
    at getResponseForW3CError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)
    at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)</status>
</kw>
<kw name="Close App" owner="common" type="TEARDOWN">
<kw name="Close All Applications" owner="AppiumLibrary">
<doc>Closes all open applications.</doc>
<status status="PASS" start="2024-10-11T00:15:15.983012" elapsed="0.001354"/>
</kw>
<status status="PASS" start="2024-10-11T00:15:15.982709" elapsed="0.001753"/>
</kw>
<status status="FAIL" start="2024-10-11T00:14:52.602390" elapsed="23.382175">Setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
    at getResponseForW3CError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)
    at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)</status>
</test>
<status status="FAIL" start="2024-10-11T00:14:52.517750" elapsed="23.468032"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Testcase">Testcase</stat>
</suite>
</statistics>
<errors>
<msg time="2024-10-11T00:15:15.979034" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
